#!/usr/bin/env bash
# Regenerates the single-file scripts in SSMS/ from the numbered folders (same order as deploy.sh).
# Run after changing any .sql file; CI fails if the committed SSMS scripts are out of date.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"
out=SSMS
mkdir -p "$out"

header() {
  cat <<HDR
/* =============================================================================================
   $1
   GENERATED by build-ssms-scripts.sh from the numbered folders. Do not edit by hand.

   $2
   ============================================================================================= */
SET NOCOUNT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO
HDR
}

append() {   # append() <file>
  printf '\n-- >>>>> %s\n' "$1"
  tr -d '\r' < "$1"
  printf '\nGO\n'
}

{
  header "ProCargo database - full install / upgrade (schema, procedures, seed data, security)" \
"How to run: open in SSMS, connect to your SQL Server (any database), press F5 (Execute).
   Safe to run again: every statement is IF NOT EXISTS / CREATE OR ALTER / MERGE, so it upgrades
   an existing ProCargo database without deleting data. Check the Messages tab ends with
   'ProCargo install completed' and shows no red errors.
   Then run ProCargo_TestData.sql for the development accounts (local testing only)."
  printf '\nUSE [master];\nGO\n'
  for f in 01-Database/*.sql; do append "$f"; done
  printf '\nUSE [ProCargo];\nGO\n'
  for d in 02-Schemas 03-Tables 04-Constraints 05-Indexes 06-Views 07-Functions 08-StoredProcedures 09-SeedData 11-Security; do
    for f in "$d"/*.sql; do append "$f"; done
  done
  printf "\nPRINT 'ProCargo install completed';\nGO\n"
} > "$out/ProCargo_Install.sql"

{
  header "ProCargo database - development test data (accounts, partners, sample bookings)" \
"How to run: AFTER ProCargo_Install.sql, open in SSMS and press F5. LOCAL TESTING ONLY - never on production.
   Every account's password is ProCargo@Dev1."
  printf '\nUSE [ProCargo];\nGO\n'
  for f in 10-TestData/*.sql; do append "$f"; done
  printf "\nPRINT 'ProCargo test data loaded';\nGO\n"
} > "$out/ProCargo_TestData.sql"

wc -l "$out"/*.sql
